### ISSUE TITLE
Using @rescript/react

### ISSUE THREAD

**Issue by earksiinni** [FormidableLabs/rescript-urql#253]
Is there a way to use `@rescript/react` instead of `reason-react` with this package? Not having `reason-react` installed causes bsb to emit errors after installing this PPX, it appears that it has `reason-react` as an (undocumented) hard requirement.

Side note, it would be super nice to be able to get bindings for just `@urql/core`.

Thanks for your work! I use the PPX in a different project that uses `reason-react` and it's absolutely wonderful.

**Comment by parkerziegler** [comment]
Hey @earksiinni 👋  There currently is no way to do this, but I hope to release a new version in the coming weeks that will. The `reason-react` / `@rescript/react` crossover, while fairly straightforward, is a pretty big breaking change for other consumers of this library. My goals are to:

- Release a new version (v4.0.0) with support for `bs-platform@9`, `urql@2`, and `@rescript/react`.
- Rename the package to `rescript-urql` and move over all publishing on `npm` to this name.

I think this should be feasible soon, but it's definitely a few key pieces away. So, TL;DR I hope to get this done in the next 2-3 weeks but I can't promise anything 😅 

I do like the idea of exposing bindings _just_ for `@urql/core` — it's long been a goal of mine to replicate some of the upstream structure of `urql` as the core team has discussed changes there. So, definitely on my radar as well!

**Comment by parkerziegler** [comment]
This isn't yet released, so I'll reopen until a new version is published.

**Comment by parkerziegler** [comment]
@earksiinni Support for `@rescript/react` has been released in `@urql/rescript` v4.0.0!
