### ISSUE TITLE
Error while running external preprocessor

### ISSUE THREAD

**Issue by SamWoolerton** [FormidableLabs/rescript-urql#294]
I'm getting a compilation error to do with the PPX when I try follow the getting started guide. The query looks fine to me (copy-pasted the whole module) so not sure why it won't compile.

Let me know if I should raise this in `@reasonml-community\graphql-ppx` instead.

Here's the command line output (on Windows; same thing happens on WSL):
```
>>>> Start compiling 
rescript: [1/3] src/utility/GraphQL.ast
FAILED: src/utility/GraphQL.ast
Fatal error: exception Yojson.Json_error("Line 1, bytes 0-33:\nInvalid token '\255\254{\000\r\000\n\000 \000 \000\"\000_\000_\000s\000c\000h\000e\000m\000a\000\"\000:'")

  We've found a bug for you!
  C:\programming\mem\src\utility\GraphQL.res

  Error while running external preprocessor
Command line: C:\programming\mem\node_modules\@reasonml-community\graphql-ppx\ppx "C:\Users\samw\AppData\Local\Temp\ppxd9e1a1GraphQL.res" "C:\Users\samw\AppData\Local\Temp\ppxe67fe2GraphQL.res"


FAILED: cannot make progress due to previous errors.
>>>> Finish compiling(exit: 1)
```

**Comment by amiralies** [comment]
It seems like the issue is related to graphql ppx.
Can you confirm your `graphql_schema.json` and `bsconfig.json` are correct?
both should be standard json (no trailing comma, no comments)

**Comment by SamWoolerton** [comment]
Thanks for the response, and agreed that it's to do with `graphql-ppx`. Should I raise this issue there instead?
These are definitely valid JSON files (format with Prettier JS works; it would fail if they were invalid).

`bsconfig.json`:
```
{
  "name": "mem",
  "namespace": false,
  "reason": { "react-jsx": 3 },
  "refmt": 3,
  "bs-dependencies": [
    "@rescript/react",
    "rescript-recoil",
    "re-dnd",
    "@urql/rescript",
    "wonka",
    "@reasonml-community/graphql-ppx"
  ],
  "ppx-flags": ["@reasonml-community/graphql-ppx/ppx"],
  "sources": [{ "dir": "src", "subdirs": true }],
  "package-specs": {
    "module": "es6",
    "in-source": true
  },
  "suffix": ".mjs",
  "warnings": {
    "number": "-3",
    "error": "+101+8"
  },
  "gentypeconfig": {
    "language": "untyped",
    "shims": []
  }
}
```

`graphql_schema.json` is way too big to put inline here but definitely valid too (PrettierJS formats it; no errors shown when viewing it in VS Code) - plus it was created automatically by an npm package, haven't touched it at all myself.

**Comment by amiralies** [comment]
Yeah I think it would be better to move the issue there.
